// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9DJGBT5_Z581DIN4jOskfQcEzlPSQ-kA',
    appId: '1:215065459780:android:8062f019dff8e5eff2d011',
    messagingSenderId: '215065459780',
    projectId: 'app-project-1b3c9',
    databaseURL: 'https://app-project-1b3c9.firebaseio.com',
    storageBucket: 'app-project-1b3c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzwtij1IfALNODMLk83yaT39PVpT8KaBQ',
    appId: '1:215065459780:ios:4570140ac8356c91f2d011',
    messagingSenderId: '215065459780',
    projectId: 'app-project-1b3c9',
    databaseURL: 'https://app-project-1b3c9.firebaseio.com',
    storageBucket: 'app-project-1b3c9.appspot.com',
    androidClientId: '215065459780-6aipd6tn6etrlb1ih9flr5kid24ml9fn.apps.googleusercontent.com',
    iosClientId: '215065459780-72e2qniillhsotfpftsogf426df5ata5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChatApps',
  );
}
